---
galaxy_info:
  role_name: common
  author: JGoutin
  description: "This role initializes a new Fedora host by performing some
                common configuration tasks."
  license: GPL-3.0
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 30
        - 31
  galaxy_tags:
    - fedora
    - system

dependencies: []
collections:
  - ansible.legacy
