---
nextcloud_admin_user: nextcloud
nextcloud_allow_web_update: false
nextcloud_applications:
  - admin_audit
  - bruteforcesettings
  - calendar
  - contacts
  - deck
  - encryption
  - files_antivirus
  - files_external
  - mail
  - maps
  - notes
  - spreed
  - tasks
  - twofactor_totp
  - twofactor_u2f
nextcloud_applications_config: []
nextcloud_system_config: []
nextcloud_token_auth_enforced: false
nextcloud_twofactor_enforced: true
nextcloud_upload_max_size: 512M
