---
namespace: jgoutin
name: home
description: Home free software self-hosting.
version: 1.0.0-beta.1
readme: readme.md
authors:
  - jgoutin
license:
  - GPL-3.0-or-later
tags:
  - fedora
  - clamav
  - dovecot
  - kodi
  - mariadb
  - mpd
  - nextcloud
  - nginx
  - php_fpm
  - postfix
  - postgresql
  - redis
  - rpmfusion

repository: https://github.com/jgoutin/ansible_home
documentation: https://github.com/jgoutin/ansible_home
issues: https://github.com/jgoutin/ansible_home/issues

dependencies: {}
