---
namespace: jgoutin
name: free_home
description: A collection of Ansible roles for home free software self-hosting.
version: 1.0.0
readme: readme.md
authors:
  - jgoutin
license:
  - BSD
tags:
  - fedora
  - clamav
  - mariadb
  - mysql
  - nextcloud
  - nginx
  - php_fpm
  - postgresql
  - redis
  - rpmfusion

repository: https://github.com/jgoutin/ansible_collection_free_home
documentation: https://github.com/jgoutin/ansible_collection_free_home
issues: https://github.com/jgoutin/ansible_collection_free_home/issues

dependencies: {}
