---
namespace: jgoutin
name: home
description: Home free software self-hosting.
version: 1.0.0-beta.3
readme: readme.md
authors:
  - jgoutin
license:
  - GPL-3.0-or-later
tags:
  - system
  - fedora
  - clamav
  - dovecot
  - kodi
  - mariadb
  - mpd
  - nextcloud
  - nginx
  - php_fpm
  - postfix
  - postgresql
  - redis
  - rpmfusion

repository: https://github.com/jgoutin/ansible_home
documentation: https://jgoutin.github.io/ansible_home/
issues: https://github.com/jgoutin/ansible_home/issues
dependencies: {}
build_ignore:
  - .gitignore
  - .idea/
  - .project/
  - .pydevproject
  - .settings/
  - .spyderproject
  - .spyproject
  - .vscode/
  - .vagrant/
  - Vagrantfile
  - playbook.yml
  - "*.tar.gz"
  - "tests/*"
  - _config.yml
  - index.md
