---
mail_domain: local
# TODO: use "is defined" instead of defaulting to ""
mail_tls_certificate:
mail_tls_certificate_key:
mail_protocol_smtp: true
mail_protocol_imap: true
mail_protocol_pop3: false
mail_protocol_submission: false
mail_protocol_lmtp: false

# Firewalld zone where allow mail services
# TODO: replace by source and link to "mail_trusted_clients"
mail_firewalld_zone: public

# Internal values
_dovecot: |
  (mail_protocol_imap | bool) or (mail_protocol_pop3 | bool) or
  (mail_protocol_submission | bool) or (mail_protocol_lmtp | bool)
_dovecot_protocols: "{{ mail_protocol_imap | ternary('imap',
                     '') }}{{ mail_protocol_pop3 | ternary(' pop3',
                     '') }}{{ mail_protocol_lmtp | ternary(' lmtp',
                     '') }}{{ mail_protocol_submission | ternary(' submission',
                     '') }}"
