---
common_dnf_automatic_restart: true
common_dnf_install_weak_deps: false
common_dnf_keepcache: false
common_dns_over_tls: opportunistic
common_fail2ban_action: "%(action_mwl)s"
common_grub_auto_hide: false
common_grub_hidden_timeout: 0
common_grub_timeout: 1
common_mail_smtp_inet_interfaces: "127.0.0.1"
common_mail_smtp_port: 465
common_mail_smtp_tls: TLS
common_os_hardening: true
common_ssh_hardening: true

# Internal values
_smtp_server: "[{{ common_mail_smtp_host }}]:{{ common_mail_smtp_port }}"
