---
galaxy_info:
  role_name: redis
  author: JGoutin
  description: This Ansible role install Redis.
  license: GPL-3.0
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 30
        - 31
  galaxy_tags:
    - fedora
    - system
    - redis

dependencies: []
