---
galaxy_info:
  role_name: mpd
  author: JGoutin
  description: "This Ansible role installs a Music Player Daemon server on
                Fedora."
  license: GPL-3.0
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 30
        - 31
  galaxy_tags:
    - fedora
    - system
    - mpd
    - music

dependencies: []
