---
- name: Ensure MPD is installed
  dnf:
    state: present
    name:
      - mpd
      - mpc
  retries: 10
  delay: 1

- name: Ensure MPD is configured
  lineinfile:
    path: /etc/mpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - line: 'music_directory "{{ mpd_music_directory }}"'
      regexp: '^#?music_directory '
      when: true
    - line: 'auto_update "{{ mpd_auto_update | ternary("yes", "no")}}"'
      regexp: '^#?auto_update '
      when: true
    - line: 'zeroconf_enabled "{{ mpd_zeroconf | ternary("yes", "no")}}"'
      regexp: '^#?zeroconf_enabled '
      when: true
    - line: 'replaygain "{{ mpd_replaygain }}"'
      regexp: '^#?replaygain '
      when: true
  when:
    - item.when

- name: Ensure MPD audio output is configured
  blockinfile:
    path: /etc/mpd.conf
    marker_begin: "audio_output {"
    marker_end: "}"
    marker: {mark}
    block: "{{ mpd_audio_output }}"
    state: present
  when: mpd_audio_output is defined

- name: Ensure SElinux booleans are configured for MPD
  seboolean:
    name: "{{ item.name }}"
    state: true
    persistent: true
  when: item.when
  with_items:
  - name: mpd_enable_homedirs
    when: true
  - name: mpd_use_cifs
    when: mpd_use_cifs | bool
  - name: mpd_use_nfs
    when: mpd_use_nfs | bool

- name: Ensure temporary directory is present
  tempfile:
    state: directory
    prefix: redis
  register: tmp_dir
  tags:
    - molecule-idempotence-notest

- name: Ensure MPD SELinux module is present
  copy:
    src: mpd_selinux.te
    dest: "{{ tmp_dir.path }}/mpd_selinux.te"
  tags:
    - molecule-idempotence-notest

- name: Ensure MPD SELinux module is activated
  command: "{{ item }}"
  with_items:
    - checkmodule -M -m -o mpd_selinux.mod mpd_selinux.te
    - semodule_package -o mpd_selinux.pp -m mpd_selinux.mod
    - semodule -i mpd_selinux.pp
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: false
  tags:
    - molecule-notest
    - molecule-idempotence-notest

- name: Ensure temporary directory is absent
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
  tags:
    - molecule-idempotence-notest

- name: Ensure MPD firewalld zone is present
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    state: present
    permanent: true
  when: mpd_firewalld_source is defined

- name: Ensure firewalld is reloaded
  command: firewall-cmd --reload
  changed_when: false
  when: mpd_firewalld_source is defined

- name: Ensure source is defined in firewalld zone
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    source: "{{ mpd_firewalld_source }}"
    state: enabled
    permanent: true
    immediate: true
  when: mpd_firewalld_source is defined

- name: Ensure firewalld allow MPD
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    service: mpd
    state: enabled
    permanent: true
    immediate: true

- name: Ensure firewalld allow Zeroconf mDNS
  firewalld:
    zone: "{{ mpd_firewalld_zone }}"
    service: mdns
    state: enabled
    permanent: true
    immediate: true
  when: mpd_zeroconf

- name: Ensure MPD socket service is started
  systemd:
    name: mpd.socket
    state: started

- name: Ensure the MPD database is up to date
  command: mpc update
  when: mpd_update | bool
  changed_when: false
