---

- name: Ensure Chrony is configured to use specified NTP server
  lineinfile:
    path: /etc/chrony.conf
    regexp: "^pool "
    line: "pool {{ ntp_server }} iburst"
  when: ntp_server is defined

- name: Ensure Chrony is restarted
  systemd:
    name: chronyd
    state: restarted
  when: ntp_server is defined
  changed_when: false

- name: Ensure DNF download performance is optimal
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: max_parallel_downloads
      value: 10
    - option: fastestmirror
      value: "true"
    - option: keepcache
      value: "{{ dnf_keepcache }}"
    - option: install_weak_deps
      value: "{{ dnf_install_weak_deps }}"

- name: Ensure DNF automatic and Fail2Ban are installed
  dnf:
    state: present
    name:
      - dnf-automatic
      - dnf-plugins-extras-tracer
      - fail2ban-firewalld
    install_weak_deps: false
  retries: 10
  delay: 1

- name: Ensure postfix is installed
  dnf:
    state: present
    name: postfix
    install_weak_deps: false
  retries: 10
  delay: 1
  when: root_mail is defined

- name: Ensure Postfix is configured with supported network protocol
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^inet_protocols ="
    line: "inet_protocols = {{ postfix_inet_protocols }}"
  when: root_mail is defined

- name: Ensure postfix service is started and enabled at boot
  systemd:
    name: postfix
    state: started
    enabled: true
  when: root_mail is defined

- name: Ensure root mails redirection is configured
  lineinfile:
    path: /etc/aliases
    regexp: "^#?root:"
    line: "root:           {{ root_mail }}"
  when: root_mail is defined

- name: Ensure mail aliases are reloaded
  command: newaliases
  changed_when: false
  when: root_mail is defined

- name: Ensure dnf-automatic-restart is installed
  get_url:
    url: "https://raw.githubusercontent.com/agross/dnf-automatic-restart/master\
          /dnf-automatic-restart"
    dest: /usr/local/sbin/dnf-automatic-restart
  retries: 10
  delay: 1

- name: Ensure dnf-automatic-install service directory is present
  file:
    path: /etc/systemd/system/dnf-automatic-install.service.d/
    state: directory

- name: Ensure dnf-automatic-restart is enabled in dnf-automatic-install
  copy:
    src: dnf-automatic-restart.conf
    dest: "/etc/systemd/system/dnf-automatic-install.service.d/\
           dnf-automatic-restart.conf"

- name: Ensure DNF automatic update service is started and enabled at boot
  systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: true

- name: Ensure Firewalld service is started and enabled at boot
  systemd:
    name: firewalld
    state: started
    enabled: true
  tags:
    - molecule-idempotence-notest

- name: Ensure Fail2ban service is started and enabled at boot
  systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Ensure admin firewalld zone is present
  firewalld:
    zone: admin
    state: present
    permanent: true
  when: firewalld_admin_source is defined

- name: Ensure firewalld is reloaded
  command: firewall-cmd --reload
  changed_when: false
  when: firewalld_admin_source is defined

- name: Ensure admin network is present admin firewalld zone
  firewalld:
    zone: admin
    source: "{{ firewalld_admin_source }}"
    state: enabled
    permanent: true
    immediate: true
  when: firewalld_admin_source is defined

- name: Ensure admin firewalld zone allow SSH
  firewalld:
    zone: admin
    service: ssh
    state: enabled
    permanent: true
    immediate: true
  when: firewalld_admin_source is defined

- name: Ensure public firewalld zone default services are dropped
  firewalld:
    zone: public
    service: "{{ item }}"
    state: disabled
    permanent: true
    immediate: true
  with_items:
    - ssh
    - dhcpv6-client
    - mdns
  when: firewalld_admin_source is defined
