---

- name: Ensure CoTURN is installed from Fedora repository
  dnf:
    state: present
    name: coturn
    install_weak_deps: false
  retries: 10
  delay: 1

- name: Ensure CoTURN is configured
  lineinfile:
    path: /etc/coturn/turnserver.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line | default(omit) }}"
    owner: root
    group: coturn
    mode: 0640
  with_items:
    - regexp: '^#?\s*listening-port='
      line: "listening-port={{ coturn_listening_port }}"
    - regexp: '^#?\s*tls-listening-port='
      line: "tls-listening-port={{ coturn_tls_listening_port }}"
    - regexp: '^#?\s*fingerprint'
      line: "fingerprint"
    - regexp: '^#?\s*use-auth-secret'
      line: "use-auth-secret"
    - regexp: '^#?\s*static-auth-secret='
      line: "static-auth-secret={{ coturn_static_auth_secret }}"
    - regexp: '^#?\s*realm='
      line: "realm={{ coturn_realm }}"
    - regexp: '^#?\s*total-quota='
      line: "total-quota={{ coturn_total_quota }}"
    - regexp: '^#?\s*bps-capacity='
      line: "bps-capacity={{ coturn_bps_capacity }}"
    - regexp: '^#?\s*no-multicast-peers'
      line: "no-multicast-peers"
    - regexp: '^#?\s*stale-nonce'
      line: "stale-nonce"
    - regexp: '^#?\s*no-tlsv1\s*$'
      line: "no-tlsv1"
    - regexp: '^#?\s*no-tlsv1_1'
      line: "no-tlsv1_1"
    - regexp: '^#?\s*dh-file='
      line: "dh-file={{ _tls_dh_params }}"
    - regexp: '^#?\s*cipher-list='
      line: cipher-list="{{ _tls_cipher }}"
    - regexp: '^#?\s*pkey='
      line: "pkey={{ _tls_key }}"
    - regexp: '^#?\s*cert='
      line: "cert={{ _tls_crt }}"

- name: Ensure TLS certificates are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.mode | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - src: "{{ coturn_tls_certificate | default(None) }}"
      dest: "{{ _tls_crt }}"
      mode: "0640"
      group: coturn
      when: "{{ coturn_tls_certificate is defined }}"
    - src: "{{ coturn_tls_certificate_key | default(None) }}"
      dest: "{{ _tls_key }}"
      mode: "0640"
      group: coturn
      when: "{{ coturn_tls_certificate_key is defined }}"
    - src: dhparam.pem
      dest: "{{ _tls_dh_params }}"
  when: item.when | default(true)

- name: Self-signed certificate warning
  debug:
    msg: "Security Warning, It is recommanded to provide a certificate signed
          by a trusted CA"
  when: coturn_tls_certificate is not defined

- name: Ensure at least an unsecure self-signed certificate is present
  command: "openssl req -x509 -newkey rsa:4096
            -keyout {{ _tls_key }} -out {{ _tls_crt }}
            -days 3650 -nodes -subj '/CN={{ coturn_realm }}'"
  args:
    creates: "{{ _tls_crt }}"
  when: coturn_tls_certificate is not defined

- name: Ensure CoTURN service parent directory is present
  file:
    path: /etc/systemd/system/coturn.service.d
    state: directory

- name: Ensure CoTURN systemd service configuration is present
  copy:
    src: coturn_service.conf
    dest: /etc/systemd/system/coturn.service.d/coturn.conf

- name: Ensure CoTURN service is started and enabled at boot
  block:
    - name: Ensure CoTURN service is started and enabled at boot
      systemd:
        name: coturn
        state: started
        enabled: true
        daemon_reload: true
  rescue:
    - name: Show service status on error
      command: systemctl status coturn --no-pager  # noqa command-instead-of-module
      failed_when: true

- name: Ensure CoTURN firewalld service is present
  template:
    src: coturn.xml.j2
    dest: /etc/firewalld/services/coturn.xml

- name: Ensure CoTURN firewalld zone is present
  ansible.posix.firewalld:
    zone: "{{ coturn_firewalld_zone }}"
    state: present
    permanent: true
  when: coturn_firewalld_source is defined

- name: Ensure firewalld is reloaded
  command: firewall-cmd --reload
  changed_when: false

- name: Ensure source is defined in firewalld zone
  ansible.posix.firewalld:
    zone: "{{ coturn_firewalld_zone }}"
    source: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items: "{{ coturn_firewalld_source }}"
  when: coturn_firewalld_source is defined

- name: Ensure firewalld allow TURN
  ansible.posix.firewalld:
    zone: "{{ coturn_firewalld_zone }}"
    service: coturn
    state: enabled
    permanent: true
    immediate: true

- name: Ensure admin firewalld zone allow TURN
  ansible.posix.firewalld:
    zone: admin
    service: coturn
    state: enabled
    permanent: true
    immediate: true
  when: common_trusted_firewalld_source is defined
